# Generated by Django 5.1.6 on 2025-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_property_options_property_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=10),
        ),
    ]
